name: CI
on: [pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                node: [12.x, 14.x, 16.x]
                react: [16.6.x, 17.0.x]
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - name: npm install, build, and test
              run: |
                  npm ci
                  npm run build
                  npm install react@${{ matrix.react }} react-dom@${{ matrix.react }} react-test-renderer@${{ matrix.react }}
                  npm run test
