name: Automated update dependencies
on:
    workflow_dispatch:
jobs:
    update-deps:
        name: Automated update dependencies
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                node-version: [14]
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.ref }}
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Setup Git
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@users.noreply.github.com
                  git config pull.ff only
            - name: Run update
              run: |
                  npm install -g npm-check-updates
                  ncu -u --packageFile ./package.json --reject react,react-dom
                  npm install
            - name: Create pull-request
              uses: peter-evans/create-pull-request@v3
              with:
                  base: master
                  branch: chore/dependencies
                  commit-message: "chore(auto): upgrade dependencies"
                  title: "[Auto] Upgrade dependencies"
                  delete-branch: true
                  signoff: true
                  body: |-
                      This PR is auto-generated by GH Action(update-deps). 
                      Please checkout the changes (especially breaking/major ones) and verify that everyting works before merging.
                  labels: |
                      dependencies
